spring.application.name=ProductApplication
server.port=8071
# MySQL DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ProductDatabase
spring.datasource.username=root
spring.datasource.password=31330Vamsi@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
